wshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_details'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

wshop/wap/urls.py
from django.urls import path
from . import views

app_name = 'wap'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<str:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

wshop/wshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("wap.urls", namespace='wap')),
    path('cart/', include("cart.urls", namespace='cart')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wshop/cart/models.py
from django.db import models

# Create your models here.

wshop/wap/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('wap:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    id = models.CharField(validators=[RegexValidator(r'^\d{12}$'),],max_length=12, primary_key=True)
    name = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    image = models.ImageField(blank=True, null=True, default=None, upload_to='products')
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    available = models.BooleanField(default=True)
    #available = models.IntegerField(null=False, default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = ('id','slug')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('wap:product_detail', args=[self.id, self.slug])

wshop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOISES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOISES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

wshop/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .cart import Cart
from .forms import CartAddProductForm
from wap.models import Product
from django.views.decorators.http import require_POST

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product=product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

wshop/wap/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'wap/product/list.html', {'category':category, 'categories':categories, 'products':products})

def product_detail(request, id, slug):
    product=get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(request, 'wap/product/detail.html', {'product':product})

wshop/cart/templates/cart/detail.html
{% extends "wap/layout.html" %}
{% load static %}

{% block title %}
    Shopping Cart
{% endblock %}


{% block content %}
    <h1>Shopping Cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Price</th>
                <th>Sum</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
        {% with product = item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img width="100"
                         src="
                         {% if product.photo %}
                            {{MEDIA_URL}}{{product.photo}}
                         {% else %}
                            {{MEDIA_URL}}products/dummyproduct.jpg
                         {% endif %}"/>
                    </a>
                </td>
                <td>{{ product.model }}</td>
                <td>{{ profuct.model }}</td>
            </tr>

        {% endfor %}
        </tbody>
    </table>


{% endblock

wshop/wap/templates/wap/index.html
{% extends "wap/layout.html" %}
{% load static %}

{% block title %}
    {% if category %}
        {{category.name}}
    {% else %}
        Products
    {% endif %}
{% endblock %}

{% block content %}
<h1>Stock</h1>

<div id="sidebar">
    <h3>Product Group</h3>
    <ul>
        <li {% if not category %}class="selected"{% endif %}>
            <a href="{% url "index" %}">All Products</a>
        </li>
        {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
            <a href="{{ c.get_absolute_url }}">{{c.name}}</a>
        </li>
        {% endfor %}
    </ul>

</div>
    <div id ="main" class="product-list">
        <h1>
            {% if category %}
                {{ category.name }}
            {% else %}
                Products
            {% endif %}
        </h1>
        {% for item in products %}
            <div class="item">
                <a href=""{{ item.get_absolute_url }}>
                    <img width="500"
                         src="
                         {% if item.photo %}
                            {{MEDIA_URL}}{{item.photo}}
                         {% else %}
                            {{MEDIA_URL}}products/dummyproduct.jpg
                         {% endif %}"/>
                </a>
                <b>{{item.name}}</b>
                <br>
                {{item.shortDescr}}
                <br>
                Продуктивність{{item.productivity}}
                <br>
                ${{item.price}}
                <br>
                <button>В кошик</button>
            </div>
        {% endfor %}
{% endblock %}

wshop/wap/templates/wap/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'wap/layout.css' %}" rel="stylesheet">
</head>

<body>
    <div id="header">
        <a href="{% url 'wap:product_list' %}" class="Logo">
            <img width="150" src="{{MEDIA_URL}}products/Wlogo.png">
        </a>
    </div>

    <div id="subheader">
        <div class="cart"> Your Cart is empty</div>
    </div>

    <div id=""content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

wshop/wap/templates/wap/product/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

wshop/wap/templates/wap/product/list.html
{% extends "wap/layout.html" %}
{% load static %}

{% block title %}
    {% if category %}
        {{category.name}}
    {% else %}
        Products
    {% endif %}
{% endblock %}

{% block content %}
<h1>Stock</h1>

<div id="sidebar">
    <h3>Categories</h3>
    <ul>
        <li {% if not category %}class="selected"{% endif %}>
            <a href="{% url 'wap:product_list' %}">All Products</a>
        </li>
        {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
            <a href="{{ c.get_absolute_url }}">{{c.name}}</a>
        </li>
        {% endfor %}
    </ul>

</div>
    <div id ="main" class="product-list">
        <h1>
            {% if category %}
                {{ category.name }}
            {% else %}
                Products
            {% endif %}
        </h1>
        {% for product in products %}
            <div class="item">
                <a href=""{{ product.get_absolute_url }}>
                    <img
                         src="
                         {% if product.image %}
                            {{MEDIA_URL}}{{product.image}}
                         {% else %}
                            {{MEDIA_URL}}products/dummyproduct.jpg
                         {% endif %}"/>
                </a>
                <a href="{{product.get_absolute_url }}">{{ product.name }}</a>
                <b>{{item.name}}</b>
                <br>
                ${{ product.price }}
            </div>
        {% endfor %}
{% endblock %}